# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode 16
      run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Build (iOS)
      run: >
        xcodebuild build -scheme SwiftBlade -sdk iphonesimulator18.0 -destination "OS=18.0,name=iPhone 16 Pro"

